const sampleListings = [
    {
        title: "Cozy Mountain Retreat",
        description: "Beautiful cabin with stunning mountain views.",
        image: {
            url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=400&q=40",
            filename: "mountain1",
        },
        price: 2500,
        location: "Manali",
        country: "India",
        geometry: { type: "Point", coordinates: [77.1892, 32.2432] },
        category: "Mountains",
    },
    {
        title: "Luxury Pool Villa",
        description: "Private villa with infinity pool.",
        image: {
            url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=40",
            filename: "pool1",
        },
        price: 5000,
        location: "Goa",
        country: "India",
        geometry: { type: "Point", coordinates: [73.8278, 15.4989] },
        category: "Amazing_pools",
    },
    {
        title: "Desert Camping Experience",
        description: "Enjoy night under stars in desert.",
        image: {
            url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=400&q=40",
            filename: "camp1",
        },
        price: 1800,
        location: "Jaisalmer",
        country: "India",
        geometry: { type: "Point", coordinates: [70.9083, 26.9157] },
        category: "Camping",
    },
    {
        title: "Arctic Ice Hotel Stay",
        description: "Experience living in ice rooms.",
        image: {
            url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400&q=40",
            filename: "arctic1",
        },
        price: 12000,
        location: "Lapland",
        country: "Finland",
        geometry: { type: "Point", coordinates: [26.0, 67.0] },
        category: "Arctic",
    },
    {
        title: "Farmhouse Stay",
        description: "Relax in peaceful green farms.",
        image: {
            url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&q=40",
            filename: "farm1",
        },
        price: 1500,
        location: "Punjab",
        country: "India",
        geometry: { type: "Point", coordinates: [75.3412, 31.1471] },
        category: "Farms",
    },
    {
        title: "Royal Castle Experience",
        description: "Stay in historic castle.",
        image: {
            url: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=400&q=40",
            filename: "castle1",
        },
        price: 8000,
        location: "Udaipur",
        country: "India",
        geometry: { type: "Point", coordinates: [73.7125, 24.5854] },
        category: "Castels",
    },
    {
        title: "Modern City Apartment",
        description: "Apartment in heart of city.",
        image: {
            url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=40",
            filename: "city1",
        },
        price: 3000,
        location: "Mumbai",
        country: "India",
        geometry: { type: "Point", coordinates: [72.8777, 19.076] },
        category: "Iconic_cities",
    },
    {
        title: "Minimal Room Stay",
        description: "Affordable clean room.",
        image: {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=40",
            filename: "room1",
        },
        price: 800,
        location: "Pune",
        country: "India",
        geometry: { type: "Point", coordinates: [73.8567, 18.5204] },
        category: "Rooms",
    },
    {
        title: "Trending Beach House",
        description: "Popular beachside property.",
        image: {
            url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=40",
            filename: "trend1",
        },
        price: 4000,
        location: "Alibaug",
        country: "India",
        geometry: { type: "Point", coordinates: [72.8739, 18.6414] },
        category: "Trending",
    },
    {
        title: "Himalayan View Cottage",
        description: "Peaceful stay in hills.",
        image: {
            url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=400&q=40",
            filename: "mountain2",
        },
        price: 2200,
        location: "Shimla",
        country: "India",
        geometry: { type: "Point", coordinates: [77.1734, 31.1048] },
        category: "Mountains",
    },
    {
        title: "Infinity Pool Resort",
        description: "Luxury stay with pool.",
        image: {
            url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=40",
            filename: "pool2",
        },
        price: 6000,
        location: "Bali",
        country: "Indonesia",
        geometry: { type: "Point", coordinates: [115.1889, -8.4095] },
        category: "Amazing_pools",
    },
    {
        title: "Jungle Camping",
        description: "Adventure camping.",
        image: {
            url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=400&q=40",
            filename: "camp2",
        },
        price: 2000,
        location: "Jim Corbett",
        country: "India",
        geometry: { type: "Point", coordinates: [78.7747, 29.53] },
        category: "Camping",
    },
    {
        title: "Snow Igloo Stay",
        description: "Unique snow experience.",
        image: {
            url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400&q=40",
            filename: "arctic2",
        },
        price: 11000,
        location: "Iceland",
        country: "Iceland",
        geometry: { type: "Point", coordinates: [-19.0208, 64.9631] },
        category: "Arctic",
    },
    {
        title: "Organic Farm Stay",
        description: "Eco-friendly farm.",
        image: {
            url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&q=40",
            filename: "farm2",
        },
        price: 1300,
        location: "Nashik",
        country: "India",
        geometry: { type: "Point", coordinates: [73.7898, 19.9975] },
        category: "Farms",
    },
    {
        title: "European Castle Stay",
        description: "Luxury castle vibes.",
        image: {
            url: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=400&q=40",
            filename: "castle2",
        },
        price: 9000,
        location: "Paris",
        country: "France",
        geometry: { type: "Point", coordinates: [2.3522, 48.8566] },
        category: "Castels",
    },
    {
        title: "Downtown Loft",
        description: "Modern city loft.",
        image: {
            url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&q=40",
            filename: "city2",
        },
        price: 3500,
        location: "Delhi",
        country: "India",
        geometry: { type: "Point", coordinates: [77.1025, 28.7041] },
        category: "Iconic_cities",
    },
    {
        title: "Budget Hostel Room",
        description: "Affordable room.",
        image: {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=40",
            filename: "room2",
        },
        price: 600,
        location: "Bangalore",
        country: "India",
        geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
        category: "Rooms",
    },
    {
        title: "Hot Trending Villa",
        description: "Top booked property.",
        image: {
            url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=40",
            filename: "trend2",
        },
        price: 4500,
        location: "Maldives",
        country: "Maldives",
        geometry: { type: "Point", coordinates: [73.2207, 3.2028] },
        category: "Trending",
    },
    {
        title: "Hilltop Camping Site",
        description: "Camping with sunrise views.",
        image: {
            url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=400&q=40",
            filename: "camp3",
        },
        price: 1700,
        location: "Lonavala",
        country: "India",
        geometry: { type: "Point", coordinates: [73.4062, 18.7546] },
        category: "Camping",
    },
    {
        title: "Small Cozy Room",
        description: "Simple and clean stay.",
        image: {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&q=40",
            filename: "room3",
        },
        price: 700,
        location: "Hyderabad",
        country: "India",
        geometry: { type: "Point", coordinates: [78.4867, 17.385] },
        category: "Rooms",
    },
];

module.exports = { data: sampleListings };
